config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'listings#index'
  resources :listings do
    resources :reviews
    resources :bookings
  end
  get 'listings/:id/destroy', to: 'listings#destroy', as: :listing_destroy
  get 'users/my_booking_requests', to: 'users#my_booking_requests', as: :my_booking_requests
  get 'users/my_bookings', to: 'users#my_bookings', as: :my_bookings
  get 'users/my_booking_requests/:id/change_status', to: 'bookings#change_status', as: :change_status
  get 'users/my_listings', to: 'users#my_listings', as: :my_listings
  resources :users, only: [:show], as: :user_profile
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :listing
  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :message, presence: true
  validates :full_name, presence: true
  validates :age, presence: true
  validates :number_of_guests, presence: true
end

app/models/listing.rb
class Listing < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  has_many :reviews, dependent: :destroy
  has_many :bookings, dependent: :destroy
  belongs_to :user
  has_many_attached :photos
  validates :title, presence: true
  validates :description, presence: true

  include PgSearch::Model
  pg_search_scope :search_by_title_and_price,
    against: [ :title, :price ],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }
end

app/models/review.rb
class Review < ApplicationRecord
   belongs_to :listing
   belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :listings
  has_many :bookings
  has_many :reviews
  validates :full_name, presence: true
  has_one_attached :photo
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, only: :home

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected 

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:full_name, :photo, :description])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :edit, :update, :destroy, :change_status]

  def index
    @bookings = Booking.all
  end

  def new
    @booking = Booking.new
    @listing = Listing.find(params[:listing_id])
  end

  def edit
  end

  def show
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.listing = Listing.find(params[:listing_id])
    if @booking.save
      redirect_to @booking.listing, notice: 'Booking succesfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT bookings/1
  def update
    if @booking.update(booking_params)
      redirect_to @booking, notice: 'Booking succesfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @booking.destroy
    redirect_to bookings_path
  end

  # Custom status action
  def change_status
    if @booking.accepted?
      @booking.accepted = false
    else
      @booking.accepted = true
    end
    @booking.save
    redirect_to my_booking_requests_path
  end

  private

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :accepted, :message, :full_name, :age, :address, :number_of_guests)
  end

end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy, :calculate_rating]

  def index
    if params[:search_by_title_and_price].nil? || params[:search_by_title_and_price].empty?
      @listings = Listing.all
    else
      @listings = Listing.search_by_title_and_price(params[:search_by_title_and_price])
    end
  end


  def show
    listing = @listing.geocode
    @markers = [{
      lat: @listing.latitude,
      lng: @listing.longitude,
      infoWindow: render_to_string(partial: "info_window", locals: { listing: listing })
    }]
    @rating = calculate_rating
  end

  def new
    @listing = Listing.new
  end

  def create
    @listing = Listing.new(listing_params)
    @listing.user = current_user
    if @listing.save
      redirect_to listing_path(@listing)
    else
      render :new
    end
  end

  def destroy
    @listing.destroy
    redirect_to listings_path
  end

  def edit
  end

  def update
    @listing.update(listing_params)
    redirect_to listing_path(@listing)
  end

  # custom rating calculation on show listing page
  def calculate_rating
    total = 0.0
    n = 0
    unless @listing.reviews == []
      @listing.reviews.each do |r|
        total += r.stars
        n += 1
      end
      total = total / n
      return "⭐️ #{total.round(2)}"
    else
      return "No review yet"
    end
  end

  private

  def set_listing
    @listing = Listing.find(params[:id])
  end

  def listing_params
    params.require(:listing).permit(:title, :description, :price, :bedrooms, :bathrooms, :house_type, :max_guests, :address, photos: [])
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @listing = Listing.find(params[:listing_id])
    @user = current_user
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @listing = Listing.find(params[:listing_id])
    @review.listing = @listing
    @review.user = current_user
    if @review.save
      redirect_to listing_path(@listing)
    else
      render :new
    end
  end

  def index
    @reviews = Review.all
    @listing = Listing.find(params[:listing_id])
  end

  def edit
    review = Review.find(params[:id])
  end

    # PATCH/PUT review/1
  def update
    @review = Review.find(params[:id])
    if @review.update(review_params)
      redirect_to @review, notice: 'Review succesfully updated.'
    else
      render :edit
    end
  end

  def destroy
    review = Review.find(params[:id])
    listing = review.listing
    review.destroy
    redirect_to listing_path(listing)
  end

  private

  def review_params
    params.require(:review).permit(:description, :stars, :user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def my_booking_requests
    @my_booking_requests = []
    current_user.listings.each do |listing|
      listing.bookings.each do |l|
        @my_booking_requests << l
      end
    end
  end

  def my_listings
    @my_listings = current_user.listings
  end

  def my_bookings
    @my_bookings = current_user.bookings
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end
  def resource
    @resource ||= User.new
  end
  def resource_class
    User
  end
  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/views/bookings/new.html.erb
<div class="form-wrapper">
  <div class="form-container">
    <h4 class="form-styling">
  Book your island now</h4>
<div class="flex-container">
  <div class="flex-item"></div>
<%= simple_form_for [@listing, @booking] do |f| %>
  <%= f.input :full_name %>
  <%= f.input :age %>
  <%= f.input :address %>
  <%= f.input :number_of_guests %>
  <%= f.input :start_date %>
  <%= f.input :end_date %>
  <%= f.input :message %>
  <%= f.button :submit %>
<% end %>
</div>
</div>
</div>
</div>
</div>

app/views/bookings/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('<%=cl_image_path @booking.listing.photos.first.key%>');">
  <div class="banner-container">
      <h3><%=@booking.listing.title%></h3>
<!--       <div id="banner-logo-seperator"></div>
 -->      <%if @booking.listing.user == current_user%>
      <div class="banner-icons">
        <%=link_to change_status_path(@booking), class: "btn-floating btn-large waves-effect waves-light green" do%><svg width="25px" height="25px" viewBox="0 0 16 16" class="bi bi-check2" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
          <path fill-rule="evenodd" d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"/>
          </svg>
        <%end%>
        <%=link_to change_status_path(@booking), class: "btn-floating btn-large waves-effect waves-light red" do%><svg width="25px" height="25px" viewBox="0 0 16 16" class="bi bi-x" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
          <path fill-rule="evenodd" d="M11.854 4.146a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708-.708l7-7a.5.5 0 0 1 .708 0z"/>
          <path fill-rule="evenodd" d="M4.146 4.146a.5.5 0 0 0 0 .708l7 7a.5.5 0 0 0 .708-.708l-7-7a.5.5 0 0 0-.708 0z"/>
          </svg>
        <%end%>
      </div>
      <%end%>
  </div>
</div>
<h3 style="text-align: center; margin: 15px; font-size: 35px;">Booking Details:</h3>
<div class="booking-details-container">
  <div class="booking-details">
    <h5>Booking accepted:
    <%if @booking.accepted%>
      <svg width="25px" height="25px" viewBox="0 0 16 16" class="bi bi-check2" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
      <path fill-rule="evenodd" d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"/>
      </svg>
    <%else%>
    <svg width="25px" height="25px" viewBox="0 0 16 16" class="bi bi-x" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
    <path fill-rule="evenodd" d="M11.854 4.146a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708-.708l7-7a.5.5 0 0 1 .708 0z"/>
    <path fill-rule="evenodd" d="M4.146 4.146a.5.5 0 0 0 0 .708l7 7a.5.5 0 0 0 .708-.708l-7-7a.5.5 0 0 0-.708 0z"/>
    </svg>
    <%end%>
    </h5>
    <h5>Start Date: <%=@booking.start_date%></h5>
    <h5>End Date: <%=@booking.end_date%></h5>
    <h5>Total Number of Guests: <%=@booking.number_of_guests%></h5>
    <h5>Name of Guest: <%=@booking.full_name%></h5>
    <h5>Age of Guest: <%=@booking.age%></h5>
    <h5>Address: <%=@booking.address%></h5>
    <h5>Email: <%=@booking.user.email%></h5>
    <h5>Message: <%=@booking.message%></h5>
  <div class="write-btn"><%= link_to '<button type="button" class="btn nav-item btn-primary">Write Review</button>'.html_safe, new_listing_review_path %></div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Islebnb - your Island, your Rules</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <!--Roboto Font for Material UI-->
  <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
</head>
<body style="margin-top: 60px">
  <%= render "shared/navbar" %>
  <div class="content">
    <div class="content-inside">
      <%= yield %>
    </div>
  </div>
  <footer class="footer">
    <%= render "shared/footer" %>
  </footer>
</body>
</html>

app/views/listings/_info_window.html.erb
<h6><%= @listing.title %></h6>
<p><%= @listing.address %></p>

app/views/listings/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1559128010-7c1ad6e1b6a5?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9);">
  <div class="banner-container">
    <img id="banner-logo" src="https://res.cloudinary.com/corneliuskf/image/upload/v1598349410/islebnb_w_rn3kyi.svg">
<!--     <div id="banner-logo-seperator"></div>
 -->    <h3>your Island, your rules</h3>
  </div>
  <div class="flex-1">
    <%= form_tag listings_path, method: :get, id: "search" do %>
    <%= submit_tag "Search", class: "btn btn-primary" %>
    <%= text_field_tag :search_by_title_and_price,
    params[:search_ƒby_title_and_price],
    class: "form-control",
      placeholder: "Find an Island"
      %>
    </div>
    <% end %>
  </div>

  <div class="listings-container">
    <% @listings.each do |listing| %>

    <div class="listing-card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= listing.photos.any? ? (cl_image_path listing.photos.first.key, heght: 280, crop: :fill) : "" %>')">
    <h5 class="listing-link">
      <%= link_to listing_path(listing) do %>
        <%= listing.title %>
        <% end %>
      </h5>
    </div>
    <% end %>
  </div>

app/views/listings/new.html.erb
<div class="form-wrapper">
  <div class="form-container">
    <h4 class="form-styling">Register your island</h4>
    <div class="form-inputs form-styling">
      <%= simple_form_for @listing do |f| %>
      <div class="row">
        <div class="col s12">
          <%= f.input :title %>
          <%= f.input :description, input_html:{class: "materialize-textarea"}%>
          <%= f.input :address, id: "listing_address" %>
        </div>
      </div>
      <div class="row">
        <div class="col s6">
          <%= f.input :bedrooms %>
        </div>
        <div class="col s6">
          <%= f.input :bathrooms %>
        </div>
      </div>
      <div class="row">
        <div class="col s6">
          <%= f.input :house_type %>
        </div>
        <div class="col s6">
          <%= f.input :price %>
        </div>
      </div>
      <div class="row">
        <div class="col s6">
          <%= f.input :max_guests %>
        </div>
        <div class="col s6">
          <%= f.input :photos, as: :file, input_html: { multiple: true, class: "mt20" } %>
        </div>
      </div>
      <div class="form-actions">
        <%= f.button :submit, "Create Island Listing", class: "btn btn-primary btn-block" %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/listings/show.html.erb
<div class="show-wrapper">
  <div class="show-container">
  <div class="row">
    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
      <div class="carousel-inner h-100">
          <%@listing.photos.each_with_index do |photo, index|%>
          <div class="carousel-item <%= index.zero? ? 'active' : '' %>">
            <%= cl_image_tag photo.key, class: "d-block w-100 h-100", height: 800, crop: 'fill' %>
          </div>
          <%end%>
      </div>
      <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
  </div>
  <div class="row ml20">
    <div class="col s8">
      <div class="d-flex">
      <div class="flex-grow-1 listings-title">
        <h6><%= @listing.title %> by <%=@listing.user.full_name%></h6>
        <span><p><%= link_to @rating, listing_reviews_path(@listing.id) %> | <%= @listing.address %></p></span>
      </div>
      <div>
      <% if @listing.user.photo.attached? %>
        <%= cl_image_tag @listing.user.photo.key, class: "circle", height: 60, width: 60, crop: 'fill' %>
      <% end %>
      </div>
    </div>
    <hr>
    <ul>
      <li>
        <div class="d-flex mb10 li-listing">
          <div>
            <i class="material-icons">home</i>
          </div>
          <div class="last-child">
            <div><h6>House type</h6></div>
            <div><p><%= @listing.house_type %></p></div>
          </div>
      </div>
    </li>
      <li>
        <div class="d-flex mb10 li-listing">
          <div>
            <i class="material-icons">hotel</i>
          </div>
          <div class="last-child">
            <div><h6>Amount of bedrooms</h6></div>
            <div><p><%= @listing.bedrooms %></p></div>
          </div>
      </div>
    </li>
      <li>
        <div class="d-flex mb10 li-listing">
          <div>
            <i class="material-icons">hot_tub</i>
          </div>
          <div class="last-child">
            <div><h6>Amount of bathrooms</h6></div>
            <div><p><%= @listing.bathrooms %></p></div>
          </div>
      </div>
    </li>
      <li>
        <div class="d-flex mb10 li-listing">
          <div>
            <i class="material-icons">group</i>
          </div>
          <div class="last-child">
            <div><h6>Max. guests allowed</h6></div>
            <div><p><%= @listing.max_guests %></p></div>
          </div>
      </div>
    </li>
      <li>
        <div class="d-flex mb10 li-listing">
          <div>
            <i class="material-icons">euro_symbol</i>
          </div>
          <div class="last-child">
            <div><h6>Price per night</h6></div>
            <div><p><%= @listing.price %></p></div>
          </div>
      </div>
    </li>
    </ul>
    <hr>
      <div class="listings-title">
      <h6>Description</h6>
        <p>
          <%= @listing.description%>
        </p>
        <a href="/listings/<%=@listing.id%>/bookings/new" class="btn btn-primary mt20" <%unless user_signed_in? %>data-toggle="modal" data-target="#myModal"<%end%>>Book this island</a>
      </div>
      <div id="myModal" class="modal fade" role="dialog">
      <div class="modal-dialog">
    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Sign up</h4>
      </div>
      <div class="modal-body">
        <%= simple_form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
        <%= f.error_notification %>
        <%= f.input :full_name%>
    <%= f.input :email,
                required: true,
                autofocus: true,
                input_html: { autocomplete: "email" }%>
    <%= f.input :password,
                required: true,
                hint: ("#{@minimum_password_length} characters minimum" if @minimum_password_length),
                input_html: { autocomplete: "new-password" } %>
    <%= f.input :password_confirmation,
                required: true,
                input_html: { autocomplete: "new-password" } %>
     <%= f.input :description,
                required: true %>
    <%= f.input :photo,
                required: true,
                as: :file %>
      </div>
      <div class="modal-footer">
        <%= f.button :submit, "Sign up", class: "btn btn-primary btn-block"%>
      </div>
    </div>
  </div>
  <%end%>
</div>
<!--Popup-->
      <%if @listing.user == current_user%>
       <%=link_to listing_destroy_path(@listing), class: "btn waves-effect waves-light red", style: "margin-top: 15px;" do%><svg width="25px" height="25px" viewBox="0 0 16 16" class="bi bi-x" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
          <path fill-rule="evenodd" d="M11.854 4.146a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708-.708l7-7a.5.5 0 0 1 .708 0z"/>
          <path fill-rule="evenodd" d="M4.146 4.146a.5.5 0 0 0 0 .708l7 7a.5.5 0 0 0 .708-.708l-7-7a.5.5 0 0 0-.708 0z"/>
          </svg>
          Delete Listing
        <%end%>
      <%end%>
    </div>
    <div class="col s4">
      <div>
        <div id="map"
     style="height: 75vh;"
     data-markers="<%= @markers.to_json %>"
     data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
     </div>
      </div>
    </div>
   </div>
      </div>
    </div>
  </div>
</div>
</div>
</div>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/reviews/index.html.erb
<div class="container col-sm-12">
  <div class="col-sm-6 row title">
    <h3> <%= @listing.title %></h3>
  </div>
    <div class="row stats col-sm-12">
      <div class="col-sm-5">
        <div class="quality"><div class="stat">Landscapes</div> <div class="points">••••• 4.5</div></div>
        <div class="quality"><div class="stat">Sea</div> <div class="points">••••• 4.5</div></div>
        <div class="quality"><div class="stat">Food</div> <div class="points">••••• 4.5</div></div>
      </div>
      <div class="col-sm-5">
        <div class="quality"><div class="stat">Lodgings</div> <div class="points">••••• 4.5</div></div>
        <div class="quality"><div class="stat">Position</div> <div class="points">••••• 4.5</div></div>
        <div class="quality"><div class="stat">Value for Money</div> <div class="points">••••• 4.5</div></div>
      </div>
    </div>
   <div class="cards row col-sm-12">
    <% @listing.reviews.each do |review| %>
    <div class="card col-sm-5">
      <div class="user"><img src=" <%= cl_image_path review.user.photo.key %> " class="circle" style="height: 50px; width: 50px;"> <%= review.user.full_name %> </div>
      <div class="content"><p><%= review.description %></p></div>
    </div>
      <% end %>
  </div>
</div>

app/views/reviews/new.html.erb
<div class="form-wrapper">
  <div class="form-container">
    <h4 class="form-styling">Write a Review</h4>
    <p> Let us know what you think of our Island</p>
    <div class="form-inputs form-styling">
      <%= simple_form_for [@listing, @review] do |f| %>
        <div class="row">
          <div class="col s12">
            <%= f.input :description, input_html:{class: "materialize-textarea"}%>
          </div>
          <div class="col s12">
            <%= f.input :stars, collection: 1..5 %>
          </div>
        </div>
        <div class="form-actions">
        <%= f.button :submit, "Submit Review", class: "btn btn-primary btn-block" %>
          </div>
      <% end %>
    </div>
  </div>
</div>

app/views/reviews/reviews.html.erb
<h1>Reviews</h1>

<%= simple_form_for @listing do |f| %>
  <%= f.input :stars %>
  <%= f.input :description %>
  <%= f.button :submit %>
<% end %>

app/views/shared/_navbar.html.erb
 <div class="nav-fixed">
  <div class="navbar justify-content-between navbar-expand navbar-light navbar-lewagon">
    <div class="navbar-left">
    <%= link_to listings_path, class: "navbar-brand" do %>
    <%= image_tag("isle.png") %>
    <% end %>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to "Features", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Pricing", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Community", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Support", "#", class: "nav-link" %>
        </li>
      </ul>
    </div>
  </div>
    <div class="navbar-buttons">
      <% if user_signed_in? %>
      <!-- avatar dropleft button -->
        <div class="dropleft">
          <img src="<%= current_user.photo.attached? ? cl_image_path(current_user.photo.key) : image_path("3376.jpg")%>" class="dropdown-toggle circle" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="width: 60px; height: 60px;">
          <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <a class="dropdown-item" href="/users/<%= current_user.id %>">My Profile</a>
            <%= link_to my_bookings_path, class: "dropdown-item" do %>
              My Bookings
            <% end %>
            <%= link_to my_booking_requests_path, class: "dropdown-item" do %>
              My Booking Requests
            <% end %>
            <%= link_to "Sign out", destroy_user_session_path, :method => :delete, class: "dropdown-item" %>
          </div>
        </div>
      <% else %>
        <%= link_to new_user_registration_path, class: "btn nav-item btn-primary" do %>
          Register
        <% end %>
        <%= link_to new_user_session_path, class: "btn nav-item btn-primary" do %>
          Sign in
        <% end %>  
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="profile-container">
  <div class="user-avatar">
    <img src="<%= cl_image_path current_user.photo.key%>" class="circle" style="height: 250px; width: 250px;">
    <%= link_to '<button type="button" class="btn-floating waves-effect waves-light red"><i class="material-icons">border_color</i></a>'.html_safe, edit_user_registration_path(@user) %>
    </div>
    <div class="user-details">
      <h4 class="card-title"><%= @user.full_name %></h4>
      <p><%=@user.description%></p>
    </div>
    <div class="d-flex justify-content-center">
      <div class="user-stats">
        <h6><i class="fas fa-house-user"></i><%=current_user.listings.size%> listing<%if current_user.listings.size > 1%>s<%end%></h6>
        <h6><i class="fas fa-cannabis"></i> Verified User </h6>
        <h6><i class="fas fa-star"></i> 4.3 Avg Stars </h6>
      </div>
    </div>
    <div class="button-actions-container">
      <div class="user-actions">
        <%= link_to new_listing_path, class: "btn nav-item btn-primary" do %>
          Add Listing
        <% end %>
        <%= link_to my_listings_path, class: "btn nav-item btn-primary" do %>
          My Listings
        <% end %>
        <%= link_to my_bookings_path, class: "btn nav-item btn-primary" do %>
          My Bookings
        <% end %>
        <%= link_to my_booking_requests_path, class: "btn nav-item btn-primary" do %>
          My Booking Requests
        <% end %>   
      </div>
    </div>
  </div>